Adds `prepareTransfer' method to `SolanaClient`
cryptoplease/dart-solana-lib pull request #23
Opened 2021-05-04 11:41 UTC by iharob

With the `prepareTransfer` method, a transfer can be created without
sending the program to Solana. Allowing it to be sent at a different
time if it was needed.

2021-05-04 20:49 UTC, ookami-kb requested changes
Since `Message` and `SignedTx` are part of public code (they are used in wallet methods, they should be exported.

Also, I don't like method `compile` being part of `TransferTx`: all the classes in `types` directory are rather "output" types used by the client. Since we're creating "transfer" message, for me, it makes sense to make it a factory method of `Message` class:

```dart
factory Message.transfer({
  required Blockhash recentBlockhash,
  required int lamports,
  required String source,
  required String destination,
}) {
  final instruction = Instruction(
    programIdIndex: 2,
    accountIndices: CompactArray.fromList([0, 1]),
    data: CompactArray.fromList([
      ...2.toSolanaBytes(32),
      ...lamports.toSolanaBytes(64),
    ]),
  );

  final message = Message(
    header: MessageHeader(1, 0, 1),
    accounts: CompactArray.fromList([
      Address.from(source),
      Address.from(destination),
      Address.from(solanaSystemProgramID),
    ]),
    recentBlockhash: recentBlockhash.blockhash,
    instructions: CompactArray.fromList([instruction]),
  );
  return message;
}
```

In that case, clients can use it like this:

```dart
final message = Message.transfer(
  recentBlockhash: await solanaClient.getRecentBlockhash(),
  lamports: transferredAmount,
  source: sourceWallet.address,
  destination: targetWallet.address,
);
final SignedTx signedTx = await sourceWallet.signMessage(message);
```

Creating a method with "and" like "build**And**SignTransferTx" always looks like responsibility being spread. With separate methods it is more straightforward and re-usable: first, we create a message; second, we sign it.

2021-05-04 20:54 UTC, iharob commented on lib/src/solana_serializable/signed_transaction.dart
> +  late final Message message;
Makes total sense. Thanks for the observation. Also, late was needed before in a different implementation and just hangs out now. Good catch.

2021-05-05 18:07 UTC, ookami-kb requested changes

2021-05-05 18:07 UTC, ookami-kb commented on lib/src/solana_serializable/message.dart
> +    return message;
```suggestion
    return Message(
      header: MessageHeader(1, 0, 1),
      accounts: CompactArray.fromList([
        Address.from(source),
        Address.from(destination),
        Address.from(solanaSystemProgramID),
      ]),
      recentBlockhash: recentBlockhash.blockhash,
      instructions: CompactArray.fromList([instruction]),
    );
```

2021-05-05 18:07 UTC, ookami-kb commented on lib/src/solana_wallet.dart
> +  Future<SignedTx> buildAndSignTransferTx({
Let's remove this method. build**And**SignTransferTx is a code smell – a method should mainly do one thing.

Using it in client will be pretty straightforward:

```dart
final message = Message.transfer(
  recentBlockhash: await solanaClient.getRecentBlockhash(),
  lamports: transferredAmount,
  source: sourceWallet.address,
  destination: targetWallet.address,
);
final SignedTx signedTx = await sourceWallet.signMessage(message);
```

2021-05-05 18:07 UTC, ookami-kb commented on lib/src/util/solana_int_encoder.dart
> +String _padTo(String what, String character, int length) =>
This function is pretty useless – you can call `padLeft` directly.

2021-05-05 18:07 UTC, ookami-kb commented on lib/src/solana_client.dart
> +  /// Send signed transaction [signedTx]
Docstring should describe what function does + dot at the end, so smth like:

```suggestion
  /// Sends signed transaction [signedTx].
```

2021-05-05 18:07 UTC, ookami-kb commented on lib/src/solana_client.dart
> +  /// Simulates sending a signed transaction [signedTx]
```suggestion
  /// Simulates sending a signed transaction [signedTx].
```

2021-05-06 08:20 UTC, ookami-kb approved these changes

2021-05-06 08:20 UTC, merged